name: Lint Workflow

on:
  push:
    branches:
      - "**"

jobs:
  PHPStan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: src/
