name: Push

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  phpstan:
    uses: katraio/.github/.github/workflows/phpstan.yml@main

  pest:
    uses: katraio/.github/.github/workflows/pest.yml@main
